name: try
run-name: ${{ github.actor }} tries to run the project
on:
    push:
        branches:
            - 'main'
jobs:
    start-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
            - name: upgrade pip
              working-directory: ./backend/
              run: python -m pip install --upgrade pip
            - name: install requirements
              working-directory: ./backend/
              run: pip install -r requirements.txt
            - name: run hello world
              working-directory: ./backend/
              run: python hello.py
            - name: test the backend
              working-directory: ./backend/
              run: pytest